CUDA_VISIBLE_DEVICES=7 python scripts/data_process/generate_key_phrases.py \
    --batch_size 128 \
    --extract_target text \
    --extract_split train \
    --src_max_length 512 \
    --tgt_max_length 100 \
    --tgt_min_length 60 \
    --begin_percentage 87 \
    --end_percentage 100 \
    --input_path ../recsum_/data/gigaword/ \
    --output_path ../recsum_/data/gigaword/kp_1.0/ \
    --identifier_column id \
    --corpus gigaword \
    --hg_model_name ankur310794/bart-base-keyphrase-generation-kpTimes
